version: "3"
services:
  db:
    image: postgres:12.1
    ports:
      - 5432:5432


  pgadmin4:
    image: dpage/pgadmin4:4.16
    ports:
      - 8080:80
    environment:
      PGADMIN_DEFAULT_EMAIL: root
      PGADMIN_DEFAULT_PASSWORD: root
    depends_on:
      - db
